version: '3.8'
services:
  postgres:
    build: 
      context: .
      dockerfile: Dockerfile-postgresql
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      local-network:
        ipv4_address: 172.23.0.13
    env_file:
      - .env
  rails:
    build:
      context: .
      dockerfile: Dockerfile 
    image: ceps-api
    container_name: rails
    tty: true 
    ports:
      - '3000:3000'
    env_file: 
      - .env
    volumes:
      - .:/ceps-api
      - gems:/usr/local/bundle/
    depends_on:
      - postgres
    external_links:
      - postgres
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_HOST: postgres
    networks:
      local-network:
        ipv4_address: 172.23.0.15

networks: 
  local-network:
    ipam:
      driver: default
      config:
        - subnet: "172.23.0.0/24"

volumes:
  postgres_data:
  gems:

