# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: pg
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
production: 
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { "localhost" } %>
development:
  <<: *default
  host: <%= ENV.fetch("POSTGRES_HOST") { "postgres" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" }  %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  database: ceps_api_development
test:
  <<: *default
  database: ceps_api_test
production:
  <<: *default
